name: run main.py

on:
  schedule:
    - cron: '*/10 * * * *' # At 00:00 every 2 hours

jobs:
  build:
    runs-on: ubuntu-latest
    steps:

      - name: checkout repo content
        uses: actions/checkout@v2 # checkout the repository content to github runner

      - name: install tesseract-ocr
        run: |
          sudo apt-get install g++ # or clang++ (presumably)
          sudo apt-get install autoconf automake libtool
          sudo apt-get install pkg-config
          sudo apt-get install libpng-dev
          sudo apt-get install libjpeg8-dev
          sudo apt-get install libtiff5-dev
          sudo apt-get install zlib1g-dev
          sudo apt-get install libwebpdemux2 libwebp-dev
          sudo apt-get install libopenjp2-7-dev
          sudo apt-get install libgif-dev
          sudo apt-get install libarchive-dev libcurl4-openssl-dev
          sudo apt install libtesseract-dev
          sudo apt-get install tesseract-ocr
          

      - name: setup python3
        uses: actions/setup-python@v4
        with:
          python-version: '3.12' # install the python version needed
          
      - name: install python packages
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          
      - name: execute py script # run main.py
        env:
          SOME_SECRET: ${{ secrets.SOME_SECRET }}
          NAMEBIO_EMAIL: ${{ secrets.NAMEBIO_EMAIL }}
          NAMEBIO_PASSWORD: ${{ secrets.NAMEBIO_PASSWORD }}
          REDIS_URL: ${{secrets.REDIS_URL}}
        run: python main.py
          
