name: run main.py

on: workflow_dispatch

jobs:
  build:
    runs-on: ubuntu-latest
    steps:

      - name: checkout repo content
        uses: actions/checkout@v2 # checkout the repository content to github runner

      - name: install tesseract-ocr
        run: |
          sudo apt-get update 
          sudo apt-get install -y software-properties-common 
          sudo add-apt-repository -y ppa:alex-p/tesseract-ocr
          sudo apt-get update 
          sudo apt-get install -y tesseract-ocr
          

      - name: setup python3
        uses: actions/setup-python@v4
        with:
          python-version: '3.12' # install the python version needed
          
      - name: install python packages
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          
      - name: execute py script # run main.py
        env:
          SOME_SECRET: ${{ secrets.SOME_SECRET }}
          NAMEBIO_EMAIL: ${{ secrets.NAMEBIO_EMAIL }}
          NAMEBIO_PASSWORD: ${{ secrets.NAMEBIO_PASSWORD }}
          REDIS_URL: ${{secrets.REDIS_URL}}
        run: python main.py
          
